[tool.poetry]
name = "wordify"
version = "0.1.0"
description = ""
authors = ["master"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
